"""creation table platform_settings

Revision ID: 68b93de1d17b
Revises: 4222e2f92537
Create Date: 2026-09-28 21:46:16.609849
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = '68b93de1d17b'
down_revision: Union[str, None] = '4222e2f92537'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auto_merge_enabled', sa.Boolean(), nullable=False),
    sa.Column('auto_merge_threshold', sa.Float(), nullable=False),
    sa.Column('suggest_merge_threshold', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('platform_settings')
    # ### end Alembic commands ###
